### ISSUE TITLE
Ready?

### ISSUE THREAD

**Issue by 7wgs0gr04v** [Viatorus/quom#15] opened 2018-12-09 14:35 UTC
Does it work yet or is it still in dev?

**Comment by optomux** [comment] 2018-12-09 15:47
Some suggestions.

- Provide option not to include system headers.
- Merging of same namespaces.
- It should put all includes at the top.

**Comment by Viatorus** [comment] 2018-12-09 20:32
Yes, it works already.

* It does not include system headers.

* Namespaces merging is not trivial at all. What benefits does is it have?

* Headers are placed where they are exactly included with #include .... All other places could result in different results.

**Comment by optomux** [comment] 2018-12-09 20:40
Well for example, several headers in a project may have a namespace in them. And when you join all of them you may end up with 40 duplicate namespaces. 

Try merging JUCE core module. You'll see what I am talking about.

**Comment by optomux** [comment] 2020-01-25 19:07
I tried it again and it seem it won't work.

`quom juce\juce_core\juce_core.h merged.h`

**Comment by Viatorus** [comment] 2020-01-26 11:39
The problem lies in this file:
https://github.com/WeAreROLI/JUCE/blob/master/modules/juce_core/system/juce_TargetPlatform.h

https://github.com/WeAreROLI/JUCE/blob/4048a5feef1c089e6d3e510994536758095959d9/modules/juce_core/system/juce_TargetPlatform.h#L39-41

I am not quit sure how Quom should handle this right. Maybe it shoudl ignore this include?

**Comment by Viatorus** [comment] 2020-01-26 12:09
I fixed it with: #26  Now such includes will be ignored by quom.

I tested quom with _juce_core_ which gave me a file with 82000 lines of code. Wow. :D

Would be nice if you could test it your self and give me feedback.

**Comment by optomux** [comment] 2020-01-26 12:46
Testing right now!!!!! I'll be testing other libs too :))))

**Comment by optomux** [comment] 2020-01-29 10:22
For some reason it won't compile :(((

**Comment by Viatorus** [comment] 2020-01-29 13:35
What won't compile? Any error logs?

**Comment by optomux** [comment] 2020-01-29 14:38
Imho this is the only one that can work.
https://github.com/cel-lang/amalgamate

**Comment by Viatorus** [comment] 2020-01-29 18:09
You speak in riddles.

**Comment by optomux** [comment] 2020-01-31 09:10
Amalgamated C/C++ file will not compile.

**Comment by Viatorus** [comment] 2020-01-31 09:26
Please [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) otherwise I cannot help you at all.

**Comment by optomux** [comment] 2020-01-31 09:31
Can't you just compile amalgamated juce_core and see?

**Comment by Viatorus** [comment] 2020-04-22 13:22
I tested it and indeed, it does not compile, because of multiple definitions.

Juce seems not to be written to be used as single header library.

**Closed by Viatorus** 2020-04-22 13:22 UTC
